# basic options
title: Ricardo Perl
# author: Ricardo Perl
logo: RicardoPerl.jpg
email: dr.ricardo.perl@gmail.com
description: My personal website
twitter_username: RicardoPerl
github_username:  perlr

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
