# basic options
title: Ricardo Perl
# author: Ricardo Perl
email: dr.ricardo.perl@gmail.com
description: My personal website
twitter_username: RicardoPerl
github_username:  perlr

# Build settings
markdown: kramdown
theme: minima
